### ISSUE TITLE
feat/Spec select for ETH SZ

### ISSUE THREAD

**Issue by leeduckgo** [BeWaterXYZ/bewater-frontend#396]
Bounty Prize: `$200`

![telegram-cloud-photo-size-5-6174890609517641556-y](https://github.com/user-attachments/assets/1d6a1ebb-f344-4240-b532-1d960bdbbde0)

赛道选择（单选）
 - Innovative Dapps
 - Open-Source Tools/Infrastructure
 - xFi
 - General

Bounty Track 选择（多选）
 - TheGrahp
 - Vara Network
 - SmartLayer Network
 - Bifrost
 - BGA(Blockchain for Good Alliance)

**Comment by Myestery** [comment]
Hi @leeduckgo 
I'll like to work on this

**Comment by leeduckgo** [comment]
> Hi @leeduckgo I'll like to work on this

Aha, this one is assigned now, but the others are openning! You could add my telegram to discuss the details:

https://t.me/leeduckgo
