### ISSUE TITLE
Basic Project Panel

### ISSUE THREAD

**Issue by leeduckgo** [BeWaterXYZ/bewater-frontend#400]
Money: `$300-$400`
The Basic Project Panel.

Impl the basic projects panel:

Projects should including the following fields:

* name
* bio
* tags
* the abstract of README
* contributors
* hackathons joined

> Ref:
> 
> https://dorahacks.io/zh/buidl

**Comment by leeduckgo** [comment]
1/ filter all the projects that have linked the github repo already.
2/  fetch the tags from the gtihub and show parallel tags with the tags now.

**Comment by yangfan3211** [comment]
todo:retrieve the project repo latest commit's timestamp, then sort the projects based on their update time, with the most recently updated ones at the top.

**Comment by yangfan3211** [comment]
todo:the GitHub tag should be validated for a valid GitHub project link when the developer fills in the project. At this time, the GitHub topic (GitHub tag) should also be retrieved and stored in the backend for convenient filtering in the future.

**Comment by leeduckgo** [comment]
TODO: check if sort by the last commit timestamp
