### ISSUE TITLE
报名后系统自动通知

### ISSUE THREAD

**Issue by leeduckgo** [BeWaterXYZ/bewater-frontend#404]
Money: `$100`

#### **背景及目标**

为了提升参赛者的体验，需要在参赛者创建队伍并提交项目信息后，平台需要自动发送系统通知和邮件通知参赛者报名成功，并告知他们可以在报名截止日期前随时更新提交的信息。

#### **需求说明**

1. **提交项目信息后的通知**
   - **系统通知**
     - 当参赛者在“我的队伍”模块中成功提交项目信息后，平台需要发送系统通知，告知参赛者报名成功。
   - **邮件通知**
     - 同时，平台还需发送一封确认邮件到参赛者的注册邮箱，通知其报名成功，并说明他们可以在报名截止日期前随时更新提交的信息。

**Comment by sparus227** [comment]
邮件通知已存在，另此issue与本仓库无关
