### ISSUE TITLE
Builderboard Module/Implement Builderboard Filter System

### ISSUE THREAD

**Issue by yangfan3211** [BeWaterXYZ/bewater-frontend#540]
Create a filtering system for Builderboard with ecosystem and track tags.
- Implement ecosystem tag system (BTC, EVM, Solana, TON, Move, Cosmos, Tron, BNB, Other)
- Implement track tag system (DeFi, Data, Gaming, AI, Meme, Social, DePIN, Tool, Infra, Other)
- Create multi-select functionality
- Implement filter logic

**Comment by leeduckgo** [comment]
Money: `250`
