### ISSUE TITLE
bug/bug in team create.

### ISSUE THREAD

**Issue by leeduckgo** [BeWaterXYZ/bewater-frontend#556]
<img width="1064" alt="image" src="https://github.com/user-attachments/assets/bf5db2cf-22a7-45ac-ab59-dd9ab3a798e7" />

**Comment by sparus227** [comment]
The validation method for customized fields in another campaign used an incorrect value type, causing all other campaigns to require validation. The issue is resolved by changing the dropdown menu value type from an array to a string.
